### ISSUE TITLE
can't get rid of it

### ISSUE THREAD

**Issue by spiderbit** [dickmao/nnhackernews#22]
If I uncommment this line from my gnus-init:
`(add-to-list 'gnus-secondary-select-methods '(nnhackernews ""))`

I get following message:

> nnhackernews--incoming: 22 requests, story +2 comment +5 
> nnhackernews-request-scan: Took 3.7873814709999998 seconds, with 1 gc runs taking 0.11170386700000279 seconds
> nnhackernews-request-group: Wrong type argument: consp, nil

So it somehow tries to still use the backend. if I delete the package and unload the module it brings still weird errors:

> if: Symbol’s function definition is void: nnhackernews--gate
> Symbol’s function definition is void: nnhackernews--rescore

After restarting emacs and gnus when I enter my email Inbox and exit it I get still following message:

> if: Symbol’s function definition is void: nnhackernews--gate

**Comment by dickmao** [comment]
Copy your `$HOME/.newsrc.eld` to `$HOME/newsrc.eld.orig` for safe keeping.

Then edit `$HOME/.newsrc.eld` and remove all s-expressions mentioning hackernews.  Sorry we couldn't make it work.

**Comment by spiderbit** [comment]
didn't work still the --gate error debugged it a bit and this seems to cause the problem:

The variable gnus-score-after-write-file-function:
```
(lambda
  (file)
  (when
      (nnhackernews--gate)
    (unless
	(member file
		(alist-get
		 (intern gnus-newsgroup-name)
		 nnhackernews-score-files))
      (push file
	    (alist-get
	     (intern gnus-newsgroup-name)
	     nnhackernews-score-files)))))
```

I just don't know from which file it reads this bullshit, ok after setting this variable to nil it seems to stop the error.

**Comment by spiderbit** [comment]
after setting that to nil the error disappears but just restartet emacs and the error is back, also tried to delete all nnhackernews files in /News but did not help.

**Comment by dickmao** [comment]
Very sorry about this!  8b0387a

There ought to be a custom-set-variable of gnus-score-after-write-file-function in your .emacs or init.el.  You should remove it with extreme prejudice.

**Comment by spiderbit** [comment]
ahh found it, no problem I am happy to get some help, that is not taken for granted for some opensource emacs package :)

**Comment by dickmao** [comment]
Sorry couldn't make it work, and thanks for your interest.  Closing.
