### ISSUE TITLE
Requesting a group scan changes subscription levels

### ISSUE THREAD

**Issue by ericsfraga** [dickmao/nnhackernews#4]
I set the subscription level of the nnhackernews groups (news, ask, show, ...) to 5. My normal scan level is 4 so that these groups are not scanned by default. However, if I C-u 5 g to scan all groups up to level 5, these groups are indeed scanned but then their subscription level is changed to 3.

Otherwise, this server works very well.  Thank you.

**Comment by dickmao** [comment]
Thank you.
