### ISSUE TITLE
lobste.rs support

### ISSUE THREAD

**Issue by ra1nb0w** [dickmao/nnhackernews#7]
Would be very nice if it supported [lobste.rs](https://lobste.rs) too.
what do you think?

Anyway, thank you for the project!

**Comment by dickmao** [comment]
I've not heard of lobste.rs, but it appears to be an HN fork (conceptually, not codewise).

It saddens me that netnews has devolved into a proliferation of javascript-heavy outposts all with their own http protocols.  The current generation of programmers were weaned on browser-everything.

Thanks for your interest.  I shall not be implementing lobste.rs.  If that changes, I'll reopen.

**Comment by ra1nb0w** [comment]
You are right!

Anyway, thank you!
